Adding mqtt_v2 plugin
David00/rpi-power-monitor pull request #124
Opened 2024-03-11 00:22 UTC by onixx

Adding mqtt_v2 plugin. Creating a new plugin vs modifying since this one only supports paho-mqtt v2.
Added features for avoiding republishing the same values if they didn't change. See readme.md

2024-03-23 01:26 UTC, David00 requested changes

2024-03-23 01:26 UTC, David00 commented on rpi_power_monitor/plugins/mqtt_v2/README.md
Hi @onixx, this looks great - thanks! The only thing I would like to see a _little bit_ more explanation of the fields available in the config section.  It may or may not be obvious for folks with differing skill levels on how they should be set to achieve the intended outcome :)

2024-03-23 01:26 UTC, David00 commented on rpi_power_monitor/plugins/mqtt_v2/mqtt_v2.py
Great use of error handling and avoidance techniques! This looks good as-is.

2024-06-03 16:28 UTC, David00 approved these changes
Thank you for adding additional details to the README - this looks good and I will go ahead and approve!

2024-06-03 16:29 UTC, merged

2024-09-17 15:53 UTC, 5ft24dave commented
@jmadden91 Any way to add a timestamp with the data that is sent?  Home assistant seems to not like data without one
Thanks

2025-07-21 16:03 UTC, nightcustard commented
I'm trying to get power_monitor talking to Home Assistant using the mqtt_v2 plugin.  
I'm currently getting a 'Failed to import enabled plugin mqtt_v2' error on restarting the power_monitor service viz:

`Jul 21 15:06:41 rpipowermonitor python3[28946]: plugin_mqtt_v2 : 2025-07-21 15:06:41 : WARNING : Failed to import enabled plugin mqtt_v2. Detail for failure:
Jul 21 15:06:41 rpipowermonitor python3[28946]: INFO : ... Starting Raspberry Pi Power Monitor
Jul 21 15:06:41 rpipowermonitor python3[28946]: INFO : Press Ctrl-c to quit...
`  

I'm running power monitor v 0.3.2 and installed paho-mqtt using 

`.venv/bin/pip install paho-mqtt>=2`

I also added the configuration block into config.toml as specified in the README.md file (ie)

`[plugins.mqtt_v2]
enabled = true
host = "192.168.27.99"
username = ""
password = ""
prefix = "powermon"
power_change = 5
voltage_change = 3
current_change = 1
pf_change = 0.05
refresh_rate = 5 # Refresh rate in seconds
max_publish_seconds = 600
`

Can` anyone who has got the mqtt_v2 plug-in working suggest why it's failing in this instance?